### ISSUE TITLE
Source installation setup for Grafana and influxDB

### ISSUE THREAD

**Issue by darshank15** [darshank15/GSoC_2020_FOSSOlogy#18]
In grafana InfluxDB [repository](https://github.com/Orange-OpenSource/fossdash) .
We only have docker installation working.
We don't have a local machine installation ( OR Source installation) script for grafana as well for influxDB.
Maybe We can have an installation script for them as well with respect to different OS supports by Fossology ( Ubuntu, Fedora, CentOS).

**Comment by darshank15** [comment]
Wrote local installation script for Grafana, InfluxDB.
https://github.com/Orange-OpenSource/fossdash/pull/1/files#diff-3fbb47e318cd8802bd325e7da9aaabe8

**Comment by NicolasToussaint** [comment]
A few comments about the [install.sh](https://github.com/Orange-OpenSource/fossdash/blob/master/install.sh) script:
- the script is limited to Debian family due to the use of `apt-get`. That's fine, but maybe the filename should reflect this.
- [line 29](https://github.com/Orange-OpenSource/fossdash/blob/989033d51d2e95edcab7d44eefaff5edbdc1b678/install.sh#L29): the `source` command, and substitution are `bash` specific: either replace by `. /etc/...` or force `/bin/bash` in the shebang
- same line, the file `/etc/lsb-release` is ubuntu specific (at least does not exist in Debian, I guess all non-Ubuntu distros). 
after that, the `influxdb.list` file is corrupted, and nothing works anymore on Debian.

I would propose the following, for a minimum quick fix:
1. rename the scripts to [un]install-ubuntu.sh
1. change shebang to `/bin/bash`
1. first check that the file `/etc/lsb-release` exists, and exit with an error if not.
1. make the script stop on first error (you may use the [bd]ash option `-e` for that)

**Comment by NicolasToussaint** [comment]
the new name suggests that the install script only applies to Ubuntu distros, and it otherwise fails gracefully, 

closing issue
